---
sudo: false

language: python

cache:
  directories:
    - $HOME/.cache/pip

install:
  - pip install -r test-requirements.txt

script:
  - ansible-lint -x 204,301,302,303,305,306,504,602 playbooks/*
  - yamllint -c .yamllint.yml playbooks tasks

notifications:
  irc:
    channels:
      - "irc.freenode.org#osism"
    template:
      - "%{result} %{repository_slug}: %{commit_subject} %{build_url}"
    skip_join: true
