---
- name: Apply role debops.grub
  hosts: all
  serial: "{{ osism_serial['grub']|default(osism_serial_default)|default(0) }}"
  become: true

  collections:
    - debops.roles02

  roles:
    - role: grub
