---
- name: Make ssh pipelining working
  hosts: all
  serial: "{{ osism_serial['pipelining']|default(osism_serial_default) }}"

  vars:
    ansible_ssh_pipelining: false

  tasks:
    - name: Do not require tty for all users
      replace:
        # NOTE: parameter changes to path after 2.3
        dest: /etc/sudoers
        regexp: "^Defaults.*requiretty$"
        replace: "Defaults !requiretty"
      become: true

- name: Apply role osism.operator
  hosts: all
  serial: "{{ osism_serial['operator']|default(osism_serial_default) }}"

  roles:
    - role: osism.operator
      tags: operator
