---
- name: Upgrade packages
  hosts: all
  serial: "{{ osism_serial['upgrade_packages']|default(osism_serial_default) }}"

  vars_prompt:
    - name: ireallymeanit
      prompt: Are you sure you want to upgrade the packages?
      default: 'no'
      private: no

  tasks:
    - name: Exit playbook, if user did not mean to upgrade the packages
      fail:
        msg: >
          "To upgrade the packages, either say 'yes' on the prompt or
           use `-e ireallymeanit=yes` on the command line when
           invoking the playbook"
      when: ireallymeanit != 'yes'

    - name: Update package cache
      apt:
        update_cache: yes
        cache_valid_time: 3600
      become: true

    - name: Upgrade packages
      apt:
        upgrade: dist
      become: true

    - name: Remove useless packages from the cache
      apt:
        autoclean: yes
      become: true

    - name: Remove dependencies that are no longer required
      apt:
        autoremove: yes
      become: true
